//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonConverterGenerator
{
    public class JsonConverterForLoginViewModel: JsonConverter<LoginViewModel>
    {
        private static ReadOnlySpan<byte> EmailBytes => new byte[5] { (byte)'E', (byte)'m', (byte)'a', (byte)'i', (byte)'l' };
        private static ReadOnlySpan<byte> PasswordBytes => new byte[8] { (byte)'P', (byte)'a', (byte)'s', (byte)'s', (byte)'w', (byte)'o', (byte)'r', (byte)'d' };
        private static ReadOnlySpan<byte> RememberMeBytes => new byte[10] { (byte)'R', (byte)'e', (byte)'m', (byte)'e', (byte)'m', (byte)'b', (byte)'e', (byte)'r', (byte)'M', (byte)'e' };
        
        public override LoginViewModel Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            // Validate that the reader's cursor is at a start token.
            if (reader.TokenType != JsonTokenType.StartObject)
            {
                throw new JsonException();
            }
            
            // Create returned object. This assumes type has public parameterless ctor.
            LoginViewModel value = new LoginViewModel();
            
            // Read all properties.
            while (true)
            {
                reader.Read();
                
                if (reader.TokenType == JsonTokenType.EndObject)
                {
                    break;
                }
                
                // Only unescaped property names are allowed.
                ReadOnlySpan<byte> propertyName = reader.HasValueSequence ? reader.ValueSequence.ToArray() : reader.ValueSpan;
                
                // Move reader cursor to property value.
                reader.Read();
                
                // Try to match property name with object properties (case sensitive).
                
                // Determine if JSON property matches 'Email'.
                if (EmailBytes.SequenceEqual(propertyName))
                {
                    value.Email = reader.GetString();
                }
                // Determine if JSON property matches 'Password'.
                else if (PasswordBytes.SequenceEqual(propertyName))
                {
                    value.Password = reader.GetString();
                }
                // Determine if JSON property matches 'RememberMe'.
                else if (RememberMeBytes.SequenceEqual(propertyName))
                {
                    value.RememberMe = reader.GetBoolean();
                }
            }
            
            return value;
        }
        
        public override void Write(Utf8JsonWriter writer, LoginViewModel value, JsonSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();
            
            writer.WriteString(EmailBytes, value.Email);
            
            writer.WriteString(PasswordBytes, value.Password);
            
            writer.WriteBoolean(RememberMeBytes, value.RememberMe);
            
            writer.WriteEndObject();
        }
    }
}
