//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonConverterGenerator
{
    public sealed class JsonConverterForDateTimeArray : JsonConverter<DateTime[]>
    {
        private JsonConverterForDateTimeArray() {}
        
        public static readonly JsonConverterForDateTimeArray Instance = new JsonConverterForDateTimeArray();
        
        public override DateTime[] Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            // Validate that the reader's cursor is at a start array token.
            if (reader.TokenType != JsonTokenType.StartArray)
            {
                throw new JsonException();
            }
            
            // Create temporary list of array elements..
            List<DateTime> elements = new List<DateTime>();
            
            // Read all elements.
            while (true)
            {
                reader.Read();
                
                if (reader.TokenType == JsonTokenType.EndArray)
                {
                    break;
                }
                
                elements.Add(reader.GetDateTime());
            }
            
            return elements.ToArray();
        }
        
        public override void Write(Utf8JsonWriter writer, DateTime[] value, JsonSerializerOptions options)
        {
            // TODO: account for value-type collections (e.g. ImmutableArray).
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartArray();
            
            foreach (DateTime element in value)
            {
                writer.WriteStringValue(element);
            }
            
            writer.WriteEndArray();
        }
    }
}
