//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonConverterGenerator
{
    public sealed class JsonConverterForMyEventsListerItemTask : JsonConverter<MyEventsListerItemTask>
    {
        private JsonConverterForMyEventsListerItemTask() {}
        
        public static readonly JsonConverterForMyEventsListerItemTask Instance = new JsonConverterForMyEventsListerItemTask();
        
        private static ReadOnlySpan<byte> NameBytes => new byte[4] { (byte)'N', (byte)'a', (byte)'m', (byte)'e' };
        private static ReadOnlySpan<byte> StartDateBytes => new byte[9] { (byte)'S', (byte)'t', (byte)'a', (byte)'r', (byte)'t', (byte)'D', (byte)'a', (byte)'t', (byte)'e' };
        private static ReadOnlySpan<byte> EndDateBytes => new byte[7] { (byte)'E', (byte)'n', (byte)'d', (byte)'D', (byte)'a', (byte)'t', (byte)'e' };
        private static ReadOnlySpan<byte> FormattedDateBytes => new byte[13] { (byte)'F', (byte)'o', (byte)'r', (byte)'m', (byte)'a', (byte)'t', (byte)'t', (byte)'e', (byte)'d', (byte)'D', (byte)'a', (byte)'t', (byte)'e' };
        
        public override MyEventsListerItemTask Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            // Validate that the reader's cursor is at a start object token.
            if (reader.TokenType != JsonTokenType.StartObject)
            {
                throw new JsonException();
            }
            
            // Create returned object. This assumes type has public parameterless ctor.
            MyEventsListerItemTask value = new MyEventsListerItemTask();
            
            // Read all properties.
            while (true)
            {
                reader.Read();
                
                if (reader.TokenType == JsonTokenType.EndObject)
                {
                    break;
                }
                
                // Only unescaped property names are allowed.
                ReadOnlySpan<byte> propertyName = reader.HasValueSequence ? reader.ValueSequence.ToArray() : reader.ValueSpan;
                
                // Move reader cursor to property value.
                reader.Read();
                
                // Try to match property name with object properties (case sensitive).
                
                // Determine if JSON property matches 'Name'.
                if (NameBytes.SequenceEqual(propertyName))
                {
                    value.Name = reader.GetString();
                }
                // Determine if JSON property matches 'StartDate'.
                else if (StartDateBytes.SequenceEqual(propertyName))
                {
                    value.StartDate = reader.GetDateTimeOffset();
                }
                // Determine if JSON property matches 'EndDate'.
                else if (EndDateBytes.SequenceEqual(propertyName))
                {
                    value.EndDate = reader.GetDateTimeOffset();
                }
            }
            
            return value;
        }
        
        public override void Write(Utf8JsonWriter writer, MyEventsListerItemTask value, JsonSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();
            
            writer.WriteString(NameBytes, value.Name);
            
            writer.WriteString(StartDateBytes, value.StartDate);
            
            writer.WriteString(EndDateBytes, value.EndDate);
            
            writer.WriteString(FormattedDateBytes, value.FormattedDate);
            
            writer.WriteEndObject();
        }
    }
}
