//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonConverterGenerator
{
    public sealed class JsonConverterForCollectionsOfPrimitives : JsonConverter<CollectionsOfPrimitives>
    {
        private JsonConverterForCollectionsOfPrimitives() {}
        
        public static readonly JsonConverterForCollectionsOfPrimitives Instance = new JsonConverterForCollectionsOfPrimitives();
        
        private static ReadOnlySpan<byte> ByteArrayBytes => new byte[9] { (byte)'B', (byte)'y', (byte)'t', (byte)'e', (byte)'A', (byte)'r', (byte)'r', (byte)'a', (byte)'y' };
        private static ReadOnlySpan<byte> DateTimeArrayBytes => new byte[13] { (byte)'D', (byte)'a', (byte)'t', (byte)'e', (byte)'T', (byte)'i', (byte)'m', (byte)'e', (byte)'A', (byte)'r', (byte)'r', (byte)'a', (byte)'y' };
        private static ReadOnlySpan<byte> DictionaryBytes => new byte[10] { (byte)'D', (byte)'i', (byte)'c', (byte)'t', (byte)'i', (byte)'o', (byte)'n', (byte)'a', (byte)'r', (byte)'y' };
        private static ReadOnlySpan<byte> ListOfIntBytes => new byte[9] { (byte)'L', (byte)'i', (byte)'s', (byte)'t', (byte)'O', (byte)'f', (byte)'I', (byte)'n', (byte)'t' };
        
        public override CollectionsOfPrimitives Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            // Validate that the reader's cursor is at a start object token.
            if (reader.TokenType != JsonTokenType.StartObject)
            {
                throw new JsonException();
            }
            
            // Create returned object. This assumes type has public parameterless ctor.
            CollectionsOfPrimitives value = new CollectionsOfPrimitives();
            
            // Read all properties.
            while (true)
            {
                reader.Read();
                
                if (reader.TokenType == JsonTokenType.EndObject)
                {
                    break;
                }
                
                // Only unescaped property names are allowed.
                ReadOnlySpan<byte> propertyName = reader.HasValueSequence ? reader.ValueSequence.ToArray() : reader.ValueSpan;
                
                // Move reader cursor to property value.
                reader.Read();
                
                // Try to match property name with object properties (case sensitive).
                
                // Determine if JSON property matches 'ByteArray'.
                if (ByteArrayBytes.SequenceEqual(propertyName))
                {
                    reader.GetBytesFromBase64();
                }
                // Determine if JSON property matches 'DateTimeArray'.
                else if (DateTimeArrayBytes.SequenceEqual(propertyName))
                {
                    value.DateTimeArray = JsonConverterForDateTimeArray.Instance.Read(ref reader, typeToConvert, options);
                }
                // Determine if JSON property matches 'Dictionary'.
                else if (DictionaryBytes.SequenceEqual(propertyName))
                {
                    value.Dictionary = JsonConverterForDictionaryStringString.Instance.Read(ref reader, typeToConvert, options);
                }
                // Determine if JSON property matches 'ListOfInt'.
                else if (ListOfIntBytes.SequenceEqual(propertyName))
                {
                    value.ListOfInt = JsonConverterForListInt32.Instance.Read(ref reader, typeToConvert, options);
                }
            }
            
            return value;
        }
        
        public override void Write(Utf8JsonWriter writer, CollectionsOfPrimitives value, JsonSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();
            
            writer.WriteBase64String(ByteArrayBytes, value.ByteArray);
            
            writer.WritePropertyName(DateTimeArrayBytes);
            JsonConverterForDateTimeArray.Instance.Write(writer, value.DateTimeArray, options);
            
            writer.WritePropertyName(DictionaryBytes);
            JsonConverterForDictionaryStringString.Instance.Write(writer, value.Dictionary, options);
            
            writer.WritePropertyName(ListOfIntBytes);
            JsonConverterForListInt32.Instance.Write(writer, value.ListOfInt, options);
            
            writer.WriteEndObject();
        }
    }
}
