//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonConverterGenerator
{
    public sealed class JsonConverterForCampaignSummaryViewModel : JsonConverter<CampaignSummaryViewModel>
    {
        private JsonConverterForCampaignSummaryViewModel() {}
        
        public static readonly JsonConverterForCampaignSummaryViewModel Instance = new JsonConverterForCampaignSummaryViewModel();
        
        private static ulong IdKey = 144115188075881545;
        private static JsonEncodedText IdText = JsonEncodedText.Encode("Id", encoder: null);
        
        private static ulong TitleKey = 360288405800905044;
        private static JsonEncodedText TitleText = JsonEncodedText.Encode("Title", encoder: null);
        
        private static ulong DescriptionKey = 18406327617078912324;
        private static JsonEncodedText DescriptionText = JsonEncodedText.Encode("Description", encoder: null);
        
        private static ulong ImageUrlKey = 18406868521031134537;
        private static JsonEncodedText ImageUrlText = JsonEncodedText.Encode("ImageUrl", encoder: null);
        
        private static ulong OrganizationNameKey = 18409142349631812175;
        private static JsonEncodedText OrganizationNameText = JsonEncodedText.Encode("OrganizationName", encoder: null);
        
        private static ulong HeadlineKey = 18405764641371284808;
        private static JsonEncodedText HeadlineText = JsonEncodedText.Encode("Headline", encoder: null);
        
        
        public override CampaignSummaryViewModel Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            // Validate that the reader's cursor is at a start object token.
            if (reader.TokenType != JsonTokenType.StartObject)
            {
                throw new JsonException();
            }
            
            // Create returned object. This assumes type has public parameterless ctor.
            CampaignSummaryViewModel value = new CampaignSummaryViewModel();
            
            // Read all properties.
            while (true)
            {
                reader.Read();
                
                if (reader.TokenType == JsonTokenType.EndObject)
                {
                    break;
                }
                
                // Only unescaped property names are allowed.
                ReadOnlySpan<byte> propertyName = reader.HasValueSequence ? reader.ValueSequence.ToArray() : reader.ValueSpan;
                
                // Move reader cursor to property value.
                reader.Read();
                
                // Try to match property name with object properties (case sensitive).
                
                // Determine if JSON property matches 'Id'.
                if (Helpers.GetKey(propertyName) == IdKey)
                {
                    value.Id = reader.GetInt32();
                }
                // Determine if JSON property matches 'Title'.
                else if (Helpers.GetKey(propertyName) == TitleKey)
                {
                    value.Title = reader.GetString();
                }
                // Determine if JSON property matches 'Description'.
                else if (Helpers.GetKey(propertyName) == DescriptionKey)
                {
                    value.Description = reader.GetString();
                }
                // Determine if JSON property matches 'ImageUrl'.
                else if (Helpers.GetKey(propertyName) == ImageUrlKey)
                {
                    value.ImageUrl = reader.GetString();
                }
                // Determine if JSON property matches 'OrganizationName'.
                else if (Helpers.GetKey(propertyName) == OrganizationNameKey)
                {
                    value.OrganizationName = reader.GetString();
                }
                // Determine if JSON property matches 'Headline'.
                else if (Helpers.GetKey(propertyName) == HeadlineKey)
                {
                    value.Headline = reader.GetString();
                }
            }
            
            return value;
        }
        
        public override void Write(Utf8JsonWriter writer, CampaignSummaryViewModel value, JsonSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();
            
            writer.WriteNumber(IdText, value.Id);
            
            writer.WriteString(TitleText, value.Title);
            
            writer.WriteString(DescriptionText, value.Description);
            
            writer.WriteString(ImageUrlText, value.ImageUrl);
            
            writer.WriteString(OrganizationNameText, value.OrganizationName);
            
            writer.WriteString(HeadlineText, value.Headline);
            
            writer.WriteEndObject();
        }
    }
}
