//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Buffers;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonConverterGenerator
{
    public sealed class JsonConverterForListActiveOrUpcomingEvent : JsonConverter<List<ActiveOrUpcomingEvent>>
    {
        private JsonConverterForListActiveOrUpcomingEvent() {}
        
        public static readonly JsonConverterForListActiveOrUpcomingEvent Instance = new JsonConverterForListActiveOrUpcomingEvent();
        
        public override List<ActiveOrUpcomingEvent> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            // Validate that the reader's cursor is at a start array token.
            if (reader.TokenType != JsonTokenType.StartArray)
            {
                throw new JsonException();
            }
            
            List<ActiveOrUpcomingEvent> elements = new List<ActiveOrUpcomingEvent>();
            
            // Read all elements.
            while (true)
            {
                reader.Read();
                
                if (reader.TokenType == JsonTokenType.EndArray)
                {
                    break;
                }
                
                elements.Add(JsonConverterForActiveOrUpcomingEvent.Instance.Read(ref reader, typeToConvert, options));
            }
            
            return elements;
        }
        
        public override void Write(Utf8JsonWriter writer, List<ActiveOrUpcomingEvent> value, JsonSerializerOptions options)
        {
            // TODO: account for value-type collections (e.g. ImmutableArray).
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartArray();
            
            foreach (ActiveOrUpcomingEvent element in value)
            {
                JsonConverterForActiveOrUpcomingEvent.Instance.Write(writer, element, options);
            }
            
            writer.WriteEndArray();
        }
    }
}
